/**
 * Country dial codes and per-country phone length rules.
 *
 * GENERATED from the mobile app so the two stay in lockstep:
 *   COUNTRIES    <- mobile/components/auth/PhoneInput.tsx
 *   PHONE_RULES  <- mobile/app/(auth)/identity.tsx
 * Re-extract from those files rather than hand-editing here.
 */

export const COUNTRIES = [
  { code: 'AT', dialCode: '+43', name: 'Austria' },
  { code: 'BE', dialCode: '+32', name: 'Belgium' },
  { code: 'BG', dialCode: '+359', name: 'Bulgaria' },
  { code: 'HR', dialCode: '+385', name: 'Croatia' },
  { code: 'CY', dialCode: '+357', name: 'Cyprus' },
  { code: 'CZ', dialCode: '+420', name: 'Czechia' },
  { code: 'DK', dialCode: '+45', name: 'Denmark' },
  { code: 'EE', dialCode: '+372', name: 'Estonia' },
  { code: 'FI', dialCode: '+358', name: 'Finland' },
  { code: 'FR', dialCode: '+33', name: 'France' },
  { code: 'DE', dialCode: '+49', name: 'Germany' },
  { code: 'GR', dialCode: '+30', name: 'Greece' },
  { code: 'HU', dialCode: '+36', name: 'Hungary' },
  { code: 'IE', dialCode: '+353', name: 'Ireland' },
  { code: 'IT', dialCode: '+39', name: 'Italy' },
  { code: 'LV', dialCode: '+371', name: 'Latvia' },
  { code: 'LT', dialCode: '+370', name: 'Lithuania' },
  { code: 'LU', dialCode: '+352', name: 'Luxembourg' },
  { code: 'MT', dialCode: '+356', name: 'Malta' },
  { code: 'NL', dialCode: '+31', name: 'Netherlands' },
  { code: 'PL', dialCode: '+48', name: 'Poland' },
  { code: 'PT', dialCode: '+351', name: 'Portugal' },
  { code: 'RO', dialCode: '+40', name: 'Romania' },
  { code: 'SK', dialCode: '+421', name: 'Slovakia' },
  { code: 'SI', dialCode: '+386', name: 'Slovenia' },
  { code: 'ES', dialCode: '+34', name: 'Spain' },
  { code: 'SE', dialCode: '+46', name: 'Sweden' },
  { code: 'AL', dialCode: '+355', name: 'Albania' },
  { code: 'AD', dialCode: '+376', name: 'Andorra' },
  { code: 'AM', dialCode: '+374', name: 'Armenia' },
  { code: 'AZ', dialCode: '+994', name: 'Azerbaijan' },
  { code: 'BY', dialCode: '+375', name: 'Belarus' },
  { code: 'BA', dialCode: '+387', name: 'Bosnia & Herzegovina' },
  { code: 'FO', dialCode: '+298', name: 'Faroe Islands' },
  { code: 'GE', dialCode: '+995', name: 'Georgia' },
  { code: 'GI', dialCode: '+350', name: 'Gibraltar' },
  { code: 'GL', dialCode: '+299', name: 'Greenland' },
  { code: 'IS', dialCode: '+354', name: 'Iceland' },
  { code: 'XK', dialCode: '+383', name: 'Kosovo' },
  { code: 'LI', dialCode: '+423', name: 'Liechtenstein' },
  { code: 'MK', dialCode: '+389', name: 'North Macedonia' },
  { code: 'MD', dialCode: '+373', name: 'Moldova' },
  { code: 'MC', dialCode: '+377', name: 'Monaco' },
  { code: 'ME', dialCode: '+382', name: 'Montenegro' },
  { code: 'NO', dialCode: '+47', name: 'Norway' },
  { code: 'RS', dialCode: '+381', name: 'Serbia' },
  { code: 'SM', dialCode: '+378', name: 'San Marino' },
  { code: 'CH', dialCode: '+41', name: 'Switzerland' },
  { code: 'UA', dialCode: '+380', name: 'Ukraine' },
  { code: 'GB', dialCode: '+44', name: 'United Kingdom' },
  { code: 'VA', dialCode: '+379', name: 'Vatican City' },
  { code: 'RU', dialCode: '+7', name: 'Russia' },
  { code: 'TR', dialCode: '+90', name: 'Turkey' },
  { code: 'US', dialCode: '+1', name: 'United States' },
  { code: 'CA', dialCode: '+1', name: 'Canada' },
  { code: 'MA', dialCode: '+212', name: 'Morocco' },
  { code: 'DZ', dialCode: '+213', name: 'Algeria' },
  { code: 'TN', dialCode: '+216', name: 'Tunisia' },
  { code: 'EG', dialCode: '+20', name: 'Egypt' },
  { code: 'NG', dialCode: '+234', name: 'Nigeria' },
  { code: 'ZA', dialCode: '+27', name: 'South Africa' },
  { code: 'AE', dialCode: '+971', name: 'United Arab Emirates' },
  { code: 'SA', dialCode: '+966', name: 'Saudi Arabia' },
  { code: 'QA', dialCode: '+974', name: 'Qatar' },
  { code: 'KW', dialCode: '+965', name: 'Kuwait' },
  { code: 'AU', dialCode: '+61', name: 'Australia' },
  { code: 'IN', dialCode: '+91', name: 'India' },
  { code: 'PK', dialCode: '+92', name: 'Pakistan' },
  { code: 'BR', dialCode: '+55', name: 'Brazil' },
  { code: 'MX', dialCode: '+52', name: 'Mexico' },
  { code: 'CN', dialCode: '+86', name: 'China' },
  { code: 'JP', dialCode: '+81', name: 'Japan' },
  { code: 'KR', dialCode: '+82', name: 'South Korea' },
  { code: 'AR', dialCode: '+54', name: 'Argentina' },
  { code: 'BO', dialCode: '+591', name: 'Bolivia' },
  { code: 'CL', dialCode: '+56', name: 'Chile' },
  { code: 'CO', dialCode: '+57', name: 'Colombia' },
  { code: 'CR', dialCode: '+506', name: 'Costa Rica' },
  { code: 'CU', dialCode: '+53', name: 'Cuba' },
  { code: 'DO', dialCode: '+1', name: 'Dominican Republic' },
  { code: 'EC', dialCode: '+593', name: 'Ecuador' },
  { code: 'SV', dialCode: '+503', name: 'El Salvador' },
  { code: 'GT', dialCode: '+502', name: 'Guatemala' },
  { code: 'GY', dialCode: '+592', name: 'Guyana' },
  { code: 'HT', dialCode: '+509', name: 'Haiti' },
  { code: 'HN', dialCode: '+504', name: 'Honduras' },
  { code: 'JM', dialCode: '+1', name: 'Jamaica' },
  { code: 'NI', dialCode: '+505', name: 'Nicaragua' },
  { code: 'PA', dialCode: '+507', name: 'Panama' },
  { code: 'PY', dialCode: '+595', name: 'Paraguay' },
  { code: 'PE', dialCode: '+51', name: 'Peru' },
  { code: 'PR', dialCode: '+1', name: 'Puerto Rico' },
  { code: 'SR', dialCode: '+597', name: 'Suriname' },
  { code: 'TT', dialCode: '+1', name: 'Trinidad & Tobago' },
  { code: 'UY', dialCode: '+598', name: 'Uruguay' },
  { code: 'VE', dialCode: '+58', name: 'Venezuela' },
  { code: 'BS', dialCode: '+1', name: 'Bahamas' },
  { code: 'BB', dialCode: '+1', name: 'Barbados' },
  { code: 'BZ', dialCode: '+501', name: 'Belize' },
  { code: 'AF', dialCode: '+93', name: 'Afghanistan' },
  { code: 'BH', dialCode: '+973', name: 'Bahrain' },
  { code: 'BD', dialCode: '+880', name: 'Bangladesh' },
  { code: 'BT', dialCode: '+975', name: 'Bhutan' },
  { code: 'BN', dialCode: '+673', name: 'Brunei' },
  { code: 'KH', dialCode: '+855', name: 'Cambodia' },
  { code: 'HK', dialCode: '+852', name: 'Hong Kong' },
  { code: 'ID', dialCode: '+62', name: 'Indonesia' },
  { code: 'IR', dialCode: '+98', name: 'Iran' },
  { code: 'IQ', dialCode: '+964', name: 'Iraq' },
  { code: 'IL', dialCode: '+972', name: 'Israel' },
  { code: 'JO', dialCode: '+962', name: 'Jordan' },
  { code: 'KZ', dialCode: '+7', name: 'Kazakhstan' },
  { code: 'KG', dialCode: '+996', name: 'Kyrgyzstan' },
  { code: 'LA', dialCode: '+856', name: 'Laos' },
  { code: 'LB', dialCode: '+961', name: 'Lebanon' },
  { code: 'MO', dialCode: '+853', name: 'Macau' },
  { code: 'MY', dialCode: '+60', name: 'Malaysia' },
  { code: 'MV', dialCode: '+960', name: 'Maldives' },
  { code: 'MN', dialCode: '+976', name: 'Mongolia' },
  { code: 'MM', dialCode: '+95', name: 'Myanmar' },
  { code: 'NP', dialCode: '+977', name: 'Nepal' },
  { code: 'KP', dialCode: '+850', name: 'North Korea' },
  { code: 'OM', dialCode: '+968', name: 'Oman' },
  { code: 'PS', dialCode: '+970', name: 'Palestine' },
  { code: 'PH', dialCode: '+63', name: 'Philippines' },
  { code: 'SG', dialCode: '+65', name: 'Singapore' },
  { code: 'LK', dialCode: '+94', name: 'Sri Lanka' },
  { code: 'SY', dialCode: '+963', name: 'Syria' },
  { code: 'TW', dialCode: '+886', name: 'Taiwan' },
  { code: 'TJ', dialCode: '+992', name: 'Tajikistan' },
  { code: 'TH', dialCode: '+66', name: 'Thailand' },
  { code: 'TL', dialCode: '+670', name: 'Timor-Leste' },
  { code: 'TM', dialCode: '+993', name: 'Turkmenistan' },
  { code: 'UZ', dialCode: '+998', name: 'Uzbekistan' },
  { code: 'VN', dialCode: '+84', name: 'Vietnam' },
  { code: 'YE', dialCode: '+967', name: 'Yemen' },
  { code: 'AO', dialCode: '+244', name: 'Angola' },
  { code: 'BJ', dialCode: '+229', name: 'Benin' },
  { code: 'BW', dialCode: '+267', name: 'Botswana' },
  { code: 'BF', dialCode: '+226', name: 'Burkina Faso' },
  { code: 'BI', dialCode: '+257', name: 'Burundi' },
  { code: 'CM', dialCode: '+237', name: 'Cameroon' },
  { code: 'CV', dialCode: '+238', name: 'Cape Verde' },
  { code: 'CF', dialCode: '+236', name: 'Central African Rep.' },
  { code: 'TD', dialCode: '+235', name: 'Chad' },
  { code: 'KM', dialCode: '+269', name: 'Comoros' },
  { code: 'CG', dialCode: '+242', name: 'Congo' },
  { code: 'CD', dialCode: '+243', name: 'DR Congo' },
  { code: 'DJ', dialCode: '+253', name: 'Djibouti' },
  { code: 'GQ', dialCode: '+240', name: 'Equatorial Guinea' },
  { code: 'ER', dialCode: '+291', name: 'Eritrea' },
  { code: 'SZ', dialCode: '+268', name: 'Eswatini' },
  { code: 'ET', dialCode: '+251', name: 'Ethiopia' },
  { code: 'GA', dialCode: '+241', name: 'Gabon' },
  { code: 'GM', dialCode: '+220', name: 'Gambia' },
  { code: 'GH', dialCode: '+233', name: 'Ghana' },
  { code: 'GN', dialCode: '+224', name: 'Guinea' },
  { code: 'GW', dialCode: '+245', name: 'Guinea-Bissau' },
  { code: 'CI', dialCode: '+225', name: 'Cote d\\' },
  { code: 'KE', dialCode: '+254', name: 'Kenya' },
  { code: 'LS', dialCode: '+266', name: 'Lesotho' },
  { code: 'LR', dialCode: '+231', name: 'Liberia' },
  { code: 'LY', dialCode: '+218', name: 'Libya' },
  { code: 'MG', dialCode: '+261', name: 'Madagascar' },
  { code: 'MW', dialCode: '+265', name: 'Malawi' },
  { code: 'ML', dialCode: '+223', name: 'Mali' },
  { code: 'MR', dialCode: '+222', name: 'Mauritania' },
  { code: 'MU', dialCode: '+230', name: 'Mauritius' },
  { code: 'MZ', dialCode: '+258', name: 'Mozambique' },
  { code: 'NA', dialCode: '+264', name: 'Namibia' },
  { code: 'NE', dialCode: '+227', name: 'Niger' },
  { code: 'RW', dialCode: '+250', name: 'Rwanda' },
  { code: 'ST', dialCode: '+239', name: 'Sao Tome & Principe' },
  { code: 'SN', dialCode: '+221', name: 'Senegal' },
  { code: 'SC', dialCode: '+248', name: 'Seychelles' },
  { code: 'SL', dialCode: '+232', name: 'Sierra Leone' },
  { code: 'SO', dialCode: '+252', name: 'Somalia' },
  { code: 'SS', dialCode: '+211', name: 'South Sudan' },
  { code: 'SD', dialCode: '+249', name: 'Sudan' },
  { code: 'TZ', dialCode: '+255', name: 'Tanzania' },
  { code: 'TG', dialCode: '+228', name: 'Togo' },
  { code: 'UG', dialCode: '+256', name: 'Uganda' },
  { code: 'ZM', dialCode: '+260', name: 'Zambia' },
  { code: 'ZW', dialCode: '+263', name: 'Zimbabwe' },
  { code: 'FJ', dialCode: '+679', name: 'Fiji' },
  { code: 'NC', dialCode: '+687', name: 'New Caledonia' },
  { code: 'NZ', dialCode: '+64', name: 'New Zealand' },
  { code: 'PG', dialCode: '+675', name: 'Papua New Guinea' },
  { code: 'WS', dialCode: '+685', name: 'Samoa' },
  { code: 'SB', dialCode: '+677', name: 'Solomon Islands' },
  { code: 'TO', dialCode: '+676', name: 'Tonga' },
  { code: 'VU', dialCode: '+678', name: 'Vanuatu' },
];

export const PHONE_RULES = {
  '+1': { min: 10, max: 10 },
  '+7': { min: 10, max: 10 },
  '+20': { min: 10, max: 10 },
  '+27': { min: 9, max: 9 },
  '+30': { min: 10, max: 10 },
  '+31': { min: 9, max: 9 },
  '+32': { min: 9, max: 9 },
  '+33': { min: 9, max: 9 },
  '+34': { min: 9, max: 9 },
  '+36': { min: 9, max: 9 },
  '+39': { min: 9, max: 10 },
  '+40': { min: 9, max: 9 },
  '+41': { min: 9, max: 9 },
  '+43': { min: 10, max: 13 },
  '+44': { min: 10, max: 10 },
  '+45': { min: 8, max: 8 },
  '+46': { min: 7, max: 9 },
  '+47': { min: 8, max: 8 },
  '+48': { min: 9, max: 9 },
  '+49': { min: 10, max: 11 },
  '+51': { min: 9, max: 9 },
  '+52': { min: 10, max: 10 },
  '+53': { min: 8, max: 8 },
  '+54': { min: 10, max: 11 },
  '+55': { min: 10, max: 11 },
  '+56': { min: 9, max: 9 },
  '+57': { min: 10, max: 10 },
  '+58': { min: 10, max: 10 },
  '+60': { min: 9, max: 10 },
  '+61': { min: 9, max: 9 },
  '+62': { min: 9, max: 12 },
  '+63': { min: 10, max: 10 },
  '+64': { min: 8, max: 10 },
  '+65': { min: 8, max: 8 },
  '+66': { min: 9, max: 9 },
  '+81': { min: 10, max: 10 },
  '+82': { min: 9, max: 10 },
  '+84': { min: 9, max: 10 },
  '+86': { min: 11, max: 11 },
  '+90': { min: 10, max: 10 },
  '+91': { min: 10, max: 10 },
  '+92': { min: 10, max: 10 },
  '+93': { min: 9, max: 9 },
  '+94': { min: 9, max: 9 },
  '+95': { min: 8, max: 10 },
  '+98': { min: 10, max: 10 },
  '+211': { min: 9, max: 9 },
  '+212': { min: 9, max: 9 },
  '+213': { min: 9, max: 9 },
  '+216': { min: 8, max: 8 },
  '+218': { min: 9, max: 9 },
  '+220': { min: 7, max: 7 },
  '+221': { min: 9, max: 9 },
  '+222': { min: 8, max: 8 },
  '+223': { min: 8, max: 8 },
  '+224': { min: 9, max: 9 },
  '+225': { min: 10, max: 10 },
  '+226': { min: 8, max: 8 },
  '+227': { min: 8, max: 8 },
  '+228': { min: 8, max: 8 },
  '+229': { min: 8, max: 8 },
  '+230': { min: 7, max: 8 },
  '+231': { min: 7, max: 9 },
  '+232': { min: 8, max: 8 },
  '+233': { min: 9, max: 9 },
  '+234': { min: 7, max: 10 },
  '+235': { min: 8, max: 8 },
  '+236': { min: 8, max: 8 },
  '+237': { min: 9, max: 9 },
  '+238': { min: 7, max: 7 },
  '+239': { min: 7, max: 7 },
  '+240': { min: 9, max: 9 },
  '+241': { min: 7, max: 8 },
  '+242': { min: 9, max: 9 },
  '+243': { min: 9, max: 9 },
  '+244': { min: 9, max: 9 },
  '+245': { min: 7, max: 7 },
  '+248': { min: 7, max: 7 },
  '+249': { min: 9, max: 9 },
  '+250': { min: 9, max: 9 },
  '+251': { min: 9, max: 9 },
  '+252': { min: 7, max: 9 },
  '+253': { min: 8, max: 8 },
  '+254': { min: 9, max: 9 },
  '+255': { min: 9, max: 9 },
  '+256': { min: 9, max: 9 },
  '+257': { min: 8, max: 8 },
  '+258': { min: 9, max: 9 },
  '+260': { min: 9, max: 9 },
  '+261': { min: 9, max: 9 },
  '+263': { min: 9, max: 10 },
  '+264': { min: 7, max: 9 },
  '+265': { min: 7, max: 9 },
  '+266': { min: 8, max: 8 },
  '+267': { min: 7, max: 8 },
  '+268': { min: 8, max: 8 },
  '+269': { min: 7, max: 7 },
  '+291': { min: 7, max: 7 },
  '+298': { min: 6, max: 6 },
  '+299': { min: 6, max: 6 },
  '+350': { min: 8, max: 8 },
  '+351': { min: 9, max: 9 },
  '+352': { min: 9, max: 9 },
  '+353': { min: 9, max: 9 },
  '+354': { min: 7, max: 9 },
  '+355': { min: 9, max: 9 },
  '+356': { min: 8, max: 8 },
  '+357': { min: 8, max: 8 },
  '+358': { min: 9, max: 10 },
  '+359': { min: 8, max: 9 },
  '+370': { min: 8, max: 8 },
  '+371': { min: 8, max: 8 },
  '+372': { min: 7, max: 8 },
  '+373': { min: 8, max: 8 },
  '+374': { min: 8, max: 8 },
  '+375': { min: 9, max: 9 },
  '+376': { min: 6, max: 9 },
  '+377': { min: 8, max: 9 },
  '+378': { min: 8, max: 10 },
  '+379': { min: 8, max: 10 },
  '+380': { min: 9, max: 9 },
  '+381': { min: 8, max: 9 },
  '+382': { min: 8, max: 8 },
  '+383': { min: 8, max: 9 },
  '+385': { min: 8, max: 9 },
  '+386': { min: 8, max: 8 },
  '+387': { min: 8, max: 8 },
  '+389': { min: 8, max: 8 },
  '+420': { min: 9, max: 9 },
  '+421': { min: 9, max: 9 },
  '+423': { min: 7, max: 9 },
  '+501': { min: 7, max: 7 },
  '+502': { min: 8, max: 8 },
  '+503': { min: 8, max: 8 },
  '+504': { min: 8, max: 8 },
  '+505': { min: 8, max: 8 },
  '+506': { min: 8, max: 8 },
  '+507': { min: 7, max: 8 },
  '+509': { min: 8, max: 8 },
  '+591': { min: 8, max: 8 },
  '+592': { min: 7, max: 7 },
  '+593': { min: 8, max: 9 },
  '+595': { min: 9, max: 9 },
  '+597': { min: 6, max: 7 },
  '+598': { min: 8, max: 8 },
  '+670': { min: 7, max: 8 },
  '+673': { min: 7, max: 7 },
  '+675': { min: 8, max: 8 },
  '+676': { min: 5, max: 7 },
  '+677': { min: 7, max: 7 },
  '+678': { min: 7, max: 7 },
  '+679': { min: 7, max: 7 },
  '+685': { min: 5, max: 7 },
  '+687': { min: 6, max: 6 },
  '+850': { min: 8, max: 10 },
  '+852': { min: 8, max: 8 },
  '+853': { min: 8, max: 8 },
  '+855': { min: 8, max: 9 },
  '+856': { min: 8, max: 10 },
  '+880': { min: 10, max: 10 },
  '+886': { min: 9, max: 9 },
  '+960': { min: 7, max: 7 },
  '+961': { min: 7, max: 8 },
  '+962': { min: 9, max: 9 },
  '+963': { min: 9, max: 9 },
  '+964': { min: 10, max: 10 },
  '+965': { min: 8, max: 8 },
  '+966': { min: 9, max: 9 },
  '+967': { min: 9, max: 9 },
  '+968': { min: 8, max: 8 },
  '+970': { min: 9, max: 9 },
  '+971': { min: 9, max: 9 },
  '+972': { min: 9, max: 9 },
  '+973': { min: 8, max: 8 },
  '+974': { min: 8, max: 8 },
  '+975': { min: 8, max: 8 },
  '+976': { min: 8, max: 8 },
  '+977': { min: 10, max: 10 },
  '+992': { min: 9, max: 9 },
  '+993': { min: 8, max: 8 },
  '+994': { min: 9, max: 9 },
  '+995': { min: 9, max: 9 },
  '+996': { min: 9, max: 9 },
  '+998': { min: 9, max: 9 },
};

/** Digits-only length check against the country's rule. Returns an error string or null. */
export function validatePhoneNumber(dialCode, localNumber) {
  const digits = String(localNumber).replace(/\D/g, '');
  if (!digits) return null;
  const rule = PHONE_RULES[dialCode] ?? { min: 6, max: 12 };
  if (digits.length < rule.min) {
    return `Too short: needs ${rule.min} digits (${digits.length} entered)`;
  }
  if (digits.length > rule.max) {
    return `Too long: max ${rule.max} digits for this country`;
  }
  return null;
}

/**
 * Strip an international/trunk prefix the user may have typed into the local
 * field, so we never build "+212212633533135". Ported verbatim from
 * mobile/app/(auth)/auth.tsx normalizeLocalDigits().
 */
export function normalizeLocalDigits(digits, dialCode) {
  const code = dialCode.replace('+', '');
  if (digits.startsWith('00' + code)) return digits.slice(2 + code.length);
  if (digits.startsWith('00')) return digits.slice(2);
  if (digits.startsWith(code) && digits.length - code.length >= 6) {
    return digits.slice(code.length);
  }
  if (digits.startsWith('0')) return digits.slice(1);
  return digits;
}

/** Best-effort default country from the browser locale, falling back to the app's default. */
export function getDefaultCountry() {
  try {
    const locales = navigator.languages?.length ? navigator.languages : [navigator.language];
    for (const loc of locales) {
      const region = new Intl.Locale(loc).maximize().region;
      const hit = COUNTRIES.find(c => c.code === region);
      if (hit) return hit;
    }
  } catch { /* Intl.Locale unsupported — fall through */ }
  return COUNTRIES[2] ?? COUNTRIES[0];
}
